"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = [ 'src/MiFlux.py' ]
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'assets/miflux-icon/miflux-icon-1024.icns',
    'includes': [ 'sip', 'PyQt5', 'twisted' ],
    'qt_plugins': [ '*' ]
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
